language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
install:
  - pip install pybuilder
  - pip install coveralls
  - pyb install_dependencies
script: "pyb -X"
after_success:
  - coveralls --verbose
